apps/finanzas/urls.py
from django.urls import path

from apps.finanzas.views.index import IndexView
from apps.finanzas.views.gastos import *
from apps.finanzas.views.ingresos import *

app_name = "finanzas"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("gastos/", ExpenseListView.as_view(), name="gastos"),
    path("gastos/nuevo/", ExpenseCreateView.as_view(), name="gastos_create"),
    path("gastos/editar/<int:pk>/", ExpenseUpdateView.as_view(), name="gastos_update"),
    path("gastos/eliminar/<int:pk>/", ExpenseDeleteView.as_view(), name="gastos_delete"),
    path("gastos/categorias/", ExpenseCategoryList.as_view(), name="gastos_categories"),
    path("gastos/categorias/nuevo/", ExpenseCategoryCreateView.as_view(), name="gastos_categories_create"),
    path("ingresos/", IncomeListView.as_view(), name="ingresos"),
    path("ingresos/nuevo/", IncomeCreateView.as_view(), name="ingresos_create"),
    path("ingresos/editar/<int:pk>/", IncomeUpdateView.as_view(), name="ingresos_update"),
    path("ingresos/eliminar/<int:pk>/", IncomeDeleteView.as_view(), name="ingresos_delete"),
    path("ingresos/categorias/", IncomeCategoryList.as_view(), name="ingresos_categories"),
    path("ingresos/categorias/nuevo/", IncomeCategoryCreateView.as_view(), name="ingresos_categories_create"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include("apps.login.urls")),
    path('finanzas/', include("apps.finanzas.urls")),
    path('negocio/', include("apps.negocio.urls")),
    path('inventario/', include("apps.inventario.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.LOCAL_DEPLOY:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/finanzas/models/inversiones.py
from django.db import models
from django.contrib.auth.models import User


class FixedTerm(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_created = models.DateField(verbose_name="Fecha de creación", auto_now_add=True)
    days = models.PositiveSmallIntegerField(verbose_name="Días")
    interest_rate = models.DecimalField(verbose_name="Tasa de interés", max_digits=5, decimal_places=2)
    starting_amount = models.DecimalField(verbose_name="Monto Inicial", max_digits=1000, decimal_places=2)
    ending_amount = models.DecimalField(verbose_name="Monto Final", max_digits=1000, decimal_places=2)

    class Meta:
        verbose_name = "Plazo Fijo"
        verbose_name_plural = "Plazos Fijos"

    def __str__(self):
        return "Plazo fijo : Dias - {}, Tasa de Interés - {}, Monto Inicial - ${}, Monto Final - ${}".format(self.days, self.interest_rate, self.starting_amount, self.ending_amount)

apps/finanzas/forms/gastos.py
import datetime

from django import forms
from django.forms import widgets

from apps.finanzas.models.gastos import Expense, ExpenseCategory


class ExpenseForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['category'] = forms.ModelChoiceField(
            widget=forms.Select(attrs={
                "class": 'form-control select2',
                "style": "width:100%",
            }),
            label="Categoría",
            required=True,
            queryset=ExpenseCategory.objects.filter(user=user).order_by('name'),
            initial=ExpenseCategory.objects.filter(user=user).order_by('name').first(),
        )
        self.fields['amount'] = forms.DecimalField(
            widget=forms.NumberInput(
                attrs={
                    "class": "form-control",
                }
            ),
            label="Monto",
            required=True,
        )
        self.fields['description'] = forms.CharField(
            widget=forms.TextInput(
                attrs={
                    "class": "form-control",
                }
            ),
            label="Descripción",
            required=True,
        )
        self.fields['date'] = forms.DateField(
            widget=forms.DateInput(
                attrs={
                    "class": "form-control",
                }
            ),
            label="Fecha",
            required=True,
            initial=datetime.date.today(),
        )

    class Meta:
        model = Expense
        fields = ['category', 'amount', 'description', 'date']

class ExpenseCategoryFrom(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'] = forms.CharField(
            widget=forms.TextInput(
                attrs={
                    "class": "form-control",
                }
            ),
            label="Nombre",
            required=True,
        )

    class Meta:
        model = ExpenseCategory
        fields = ['name',]

apps/finanzas/views/gastos.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from requests.api import delete
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from apps.finanzas.models.gastos import Expense, ExpenseCategory
from apps.finanzas.forms.gastos import ExpenseForm, ExpenseCategoryFrom
from apps.finanzas.services import get_total_expenses, update_monthly_audit


class ExpenseCreateView(CreateView):
    template_name = "finanzas/gastos/create.html"
    model = Expense
    form_class = ExpenseForm
    success_url = reverse_lazy('finanzas:gastos')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST, user=request.user)
        if form.is_valid():
            expense = form.save(commit=False)
            expense.user = request.user
            expense.save()
            update_monthly_audit(request.user, expense.date.month, expense.date.year)
            return HttpResponseRedirect(self.get_success_url())
        else:
            self.object = None
            context = self.get_context_data(**kwargs)
            context['errors'] = form.errors
            return render(request, self.template_name, context)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Nuevo Gasto"
        return context


class ExpenseListView(ListView):
    template_name = "finanzas/gastos/list.html"
    model = Expense

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        expenses = Expense.objects.filter(user=self.request.user)
        return expenses

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Gastos"
        context['total'] = get_total_expenses(self.request.user)
        context['new_button'] = "Nuevo Gasto"
        context['new_button_url'] = reverse("finanzas:gastos_create")
        return context


class ExpenseUpdateView(UpdateView):
    model = Expense
    template_name = "finanzas/gastos/update.html"
    form_class = ExpenseForm
    success_url = reverse_lazy('finanzas:gastos')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save()
        update_monthly_audit(self.request.user, self.object.date.month, self.object.date.year)
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Editar Gasto"
        return context


class ExpenseDeleteView(DeleteView):
    model = Expense
    template_name = "finanzas/gastos/delete.html"
    success_url = reverse_lazy('finanzas:gastos')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        month = self.object.date.month
        year = self.object.date.year
        self.object.delete()
        update_monthly_audit(request.user, month, year)
        return HttpResponseRedirect(success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Eliminar Gasto"
        return context


class ExpenseCategoryList(ListView):
    model = ExpenseCategory
    template_name = "finanzas/gastos/category_list.html"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        expenses = ExpenseCategory.objects.filter(user=self.request.user)
        return expenses

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Categorías de gastos"
        context['new_button'] = "Nueva Categoría"
        context['new_button_url'] = reverse("finanzas:gastos_categories_create")
        return context


class ExpenseCategoryCreateView(CreateView):
    model = ExpenseCategory
    template_name = "finanzas/gastos/category_create.html"
    success_url = reverse_lazy('finanzas:gastos_categories')
    form_class = ExpenseCategoryFrom

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        if form.is_valid():
            income = form.save(commit=False)
            income.user = request.user
            income.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            self.object = None
            context = self.get_context_data(**kwargs)
            context['errors'] = form.errors
            return render(request, self.template_name, context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Nueva Categoría de Gasto"
        return context

apps/finanzas/views/index.py
import datetime

from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from apps.finanzas.services import get_dollar_price
from apps.finanzas.models.balance import MonthlyAudit


class IndexView(TemplateView):
    template_name = "finanzas/index.html"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Inicio"
        context['blue_dollar'] = get_dollar_price()
        context['month_data'] = MonthlyAudit.objects.last()
        return context

apps/finanzas/views/ingresos.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from apps.finanzas.models.ingresos import Income, IncomeCategory
from apps.finanzas.forms.ingresos import IncomeForm, IncomeCategoryFrom
from apps.finanzas.services import get_total_expenses, update_monthly_audit


class IncomeCreateView(CreateView):
    template_name = "finanzas/ingresos/create.html"
    model = Income
    form_class = IncomeForm
    success_url = reverse_lazy('finanzas:ingresos')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST, user=request.user)
        if form.is_valid():
            income = form.save(commit=False)
            income.user = request.user
            income.save()
            update_monthly_audit(request.user, income.date.month, income.date.year)
            return HttpResponseRedirect(self.get_success_url())
        else:
            self.object = None
            context = self.get_context_data(**kwargs)
            context['errors'] = form.errors
            return render(request, self.template_name, context)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Nuevo Ingreso"
        return context


class IncomeListView(ListView):
    template_name = "finanzas/ingresos/list.html"
    model = Income

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        incomes = Income.objects.filter(user=self.request.user)
        return incomes

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Ingresos"
        context['total'] = get_total_expenses(self.request.user)
        context['new_button'] = "Nuevo Ingreso"
        context['new_button_url'] = reverse("finanzas:ingresos_create")
        return context


class IncomeUpdateView(UpdateView):
    model = Income
    template_name = "finanzas/ingresos/update.html"
    form_class = IncomeForm
    success_url = reverse_lazy('finanzas:ingresos')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save()
        update_monthly_audit(self.request.user, self.object.date.month, self.object.date.year)
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Editar Ingreso"
        return context


class IncomeDeleteView(DeleteView):
    model = Income
    template_name = "finanzas/ingresos/delete.html"
    success_url = reverse_lazy('finanzas:ingresos')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        month = self.object.date.month
        year = self.object.date.year
        self.object.delete()
        update_monthly_audit(request.user, month, year)
        return HttpResponseRedirect(success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Eliminar Ingreso"
        return context


class IncomeCategoryList(ListView):
    model = IncomeCategory
    template_name = "finanzas/ingresos/category_list.html"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        incomes = IncomeCategory.objects.filter(user=self.request.user)
        return incomes

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Categorías de ingresos"
        context['new_button'] = "Nueva Categoría"
        context['new_button_url'] = reverse("finanzas:ingresos_categories_create")
        return context

class IncomeCategoryCreateView(CreateView):
    model = IncomeCategory
    template_name = "finanzas/ingresos/category_create.html"
    success_url = reverse_lazy('finanzas:ingresos_categories')
    form_class = IncomeCategoryFrom

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        if form.is_valid():
            income = form.save(commit=False)
            income.user = request.user
            income.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            self.object = None
            context = self.get_context_data(**kwargs)
            context['errors'] = form.errors
            return render(request, self.template_name, context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Nueva Categoría de Ingreso"
        return context

templates/finanzas/ingresos/category_create.html
{% extends 'common/base.html' %}
{% load static crispy_forms_tags %}

{% block content %}
    <section class="content">
        <div class="container-fluid">
            <div class="card card-default">
                <div class="card-header">
                  <h3 class="card-title">Datos necesarios</h3>
      
                  <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                      <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                      <i class="fas fa-times"></i>
                    </button>
                  </div>
                </div>
                <!-- /.card-header -->
                <form action="." method="post">
                    {% csrf_token %}
                    <div class="card-body">
                        <div class="row">
                          <div class="col-md-12">
                              {{ form.name|as_crispy_field }}
                          </div>
                        <!-- /.row -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer text-center">
                        <button class="btn btn-primary" type="submit">Guardar</button>
                        <a href="{% url 'finanzas:ingresos_categories' %}" class="btn btn-secondary">Cancelar</a>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

templates/finanzas/ingresos/category_list.html
{% extends 'common/list.html' %}
{% load static %}

{% block table_headers %}
    <th>Nombre</th>
    <th>Acciones</th>
{% endblock %}

{% block table_rows %}
    <td>{{ obj.name }}</td>
    <td>
        <a href="" class="btn btn-primary"><i class="fas fa-pen-square"></i> Editar</a>
        <a href="" class="btn btn-danger"><i class="fas fa-trash"></i> Eliminar</a>
    </td>
{% endblock %}

{% block table_footer %}
    <th>Nombre</th>
    <th>Acciones</th>
{% endblock %}

templates/finanzas/ingresos/create.html
{% extends 'common/base.html' %}
{% load static crispy_forms_tags %}

{% block extra_styles %}
    <link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}">
{% endblock %}

{% block content %}
    <section class="content">
        <div class="container-fluid">
            <div class="card card-default">
                <div class="card-header">
                  <h3 class="card-title">Datos necesarios</h3>
      
                  <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                      <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                      <i class="fas fa-times"></i>
                    </button>
                  </div>
                </div>
                <!-- /.card-header -->
                <form action="." method="post">
                    {% csrf_token %}
                    <div class="card-body">
                        <div class="row">
                          <div class="col-md-12">
                              {{ form.category|as_crispy_field }}
                              {{ form.date|as_crispy_field }}
                              {{ form.amount|as_crispy_field }}
                              {{ form.description|as_crispy_field }}
                          </div>
                        <!-- /.row -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer text-center">
                        <button class="btn btn-primary" type="submit">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

{% block extra_scripts %}
    <script src="{% static 'plugins/select2/js/select2.full.min.js' %}"></script>
    <script>
        $('.select2').select2({
            theme: 'bootstrap4'
        });
    </script>
{% endblock %}

templates/finanzas/ingresos/delete.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <form action="." method="post">
                    {% csrf_token %}
                    <div class="card card-danger">
                        <div class="card-header">
                        <h4 class="card-title w-100">
                            <a class="d-block w-100" data-toggle="collapse" href="#collapseTwo" aria-expanded="true">
                            Atención
                            </a>
                        </h4>
                        </div>
                        <div id="collapseTwo" class="collapse show" data-parent="#accordion">
                        <div class="card-body">
                            ¿Está seguro de querer eliminar el ingreso por ${{object.amount}} del {{object.date}}?
                        </div>
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-danger"><i class="fas fa-trash-alt"></i> Eliminar</button>
                            <a href="{% url 'finanzas:ingresos' %}" class="btn btn-secondary">Cancelar</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/finanzas/ingresos/list.html
{% extends 'common/list.html' %}
{% load static %}

{% block table_headers %}
    <th>ID</th>
    <th>Fecha</th>
    <th>Categoría</th>
    <th>Monto</th>
    <th>Descripción</th>
    <th>Acciones</th>
{% endblock %}

{% block table_rows %}
    <td>{{ obj.id }}</td>
    <td>{{ obj.date }}</td>
    <td>{{ obj.category }}</td>
    <td>$ {{ obj.amount }}</td>
    <td>{{ obj.description }}</td>
    <td>
        <a href="{% url 'finanzas:ingresos_update' obj.id %}" class="btn btn-primary"><i class="fas fa-pen-square"></i> Editar</a>
        <a href="{% url 'finanzas:ingresos_delete' obj.id %}" class="btn btn-danger"><i class="fas fa-trash"></i> Eliminar</a>
    </td>
{% endblock %}

{% block table_footer %}
    <th>ID</th>
    <th>Fecha</th>
    <th>Categoría</th>
    <th>Monto</th>
    <th>Descripción</th>
    <th>Acciones</th>
{% endblock %}

templates/finanzas/ingresos/update.html
{% extends 'common/base.html' %}
{% load static crispy_forms_tags %}

{% block extra_styles %}
    <link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}">
{% endblock %}

{% block content %}
    <section class="content">
        <div class="container-fluid">
            <div class="card card-default">
                <div class="card-header">
                  <h3 class="card-title">Datos necesarios</h3>
      
                  <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                      <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                      <i class="fas fa-times"></i>
                    </button>
                  </div>
                </div>
                <!-- /.card-header -->
                <form action="." method="post">
                    {% csrf_token %}
                    <div class="card-body">
                        <div class="row">
                          <div class="col-md-12">
                              {{ form.category|as_crispy_field }}
                              {{ form.date|as_crispy_field }}
                              {{ form.amount|as_crispy_field }}
                              {{ form.description|as_crispy_field }}
                          </div>
                        <!-- /.row -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer text-center">
                        <button class="btn btn-primary" type="submit">Guardar</button>
                        <a href="{% url 'finanzas:ingresos' %}" class="btn btn-secondary">Cancelar</a>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

{% block extra_scripts %}
    <script src="{% static 'plugins/select2/js/select2.full.min.js' %}"></script>
    <script>
        $('.select2').select2({
            theme: 'bootstrap4'
        });
    </script>
{% endblock %}