apps/finanzas/urls.py
from django.urls import path

from apps.finanzas.views.index import IndexView
from apps.finanzas.views.gastos import *
from apps.finanzas.views.ingresos import *

app_name = "finanzas"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("gastos/", ExpenseListView.as_view(), name="gastos"),
    path("gastos/nuevo/", ExpenseCreateView.as_view(), name="gastos_create"),
    path("gastos/editar/<int:pk>/", ExpenseUpdateView.as_view(), name="gastos_update"),
    path("gastos/eliminar/<int:pk>/", ExpenseDeleteView.as_view(), name="gastos_delete"),
    path("gastos/categorias/", ExpenseCategoryList.as_view(), name="gastos_categories"),
    path("gastos/categorias/nuevo/", ExpenseCategoryCreateView.as_view(), name="gastos_categories_create"),
    path("ingresos/", IncomeListView.as_view(), name="ingresos"),
    path("ingresos/nuevo/", IncomeCreateView.as_view(), name="ingresos_create"),
    path("ingresos/editar/<int:pk>/", IncomeUpdateView.as_view(), name="ingresos_update"),
    path("ingresos/eliminar/<int:pk>/", IncomeDeleteView.as_view(), name="ingresos_delete"),
    path("ingresos/categorias/", IncomeCategoryList.as_view(), name="ingresos_categories"),
    path("ingresos/categorias/nuevo/", IncomeCategoryCreateView.as_view(), name="ingresos_categories_create"),
]

apps/login/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from apps.login.views.login import LoginFormView, ChangePasswordView

app_name = "login"

urlpatterns = [
    path('', LoginFormView.as_view(), name="login"),
    path('change_password/', ChangePasswordView.as_view(), name="change_password"),
    path('logout/', LogoutView.as_view(next_page='login:login'), name="logout"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include("apps.login.urls")),
    path('finanzas/', include("apps.finanzas.urls")),
    path('negocio/', include("apps.negocio.urls")),
    path('inventario/', include("apps.inventario.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.LOCAL_DEPLOY:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/common/aside.html
{% load static %}
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="" class="brand-link">
      <img src="{% static 'img/guia-financiera.png' %}" alt="Finanzas" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">Finanzas</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{% static 'img/user.png' %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{ request.user.username }}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            <a href="{% url 'finanzas:index' %}" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
              </p>
            </a>
          </li>
          <li class="nav-item menu-open">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-hand-holding-usd"></i>
              <p>
                Ingresos
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'finanzas:ingresos' %}" class="nav-link">
                  <i class="fas fa-clipboard-list nav-icon"></i>
                  <p>Ver Ingresos</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'finanzas:ingresos_categories' %}" class="nav-link">
                  <i class="fas fa-poll-h nav-icon"></i>
                  <p>Categorías de ingresos</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item menu-open">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-credit-card"></i>
              <p>
                Gastos
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'finanzas:gastos' %}" class="nav-link">
                  <i class="fas fa-clipboard-list nav-icon"></i>
                  <p>Ver Gastos</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'finanzas:gastos_categories' %}" class="nav-link">
                  <i class="fas fa-poll-h nav-icon"></i>
                  <p>Categorías de gastos</p>
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

templates/common/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{{ title }} | Finanzas</title>

    <link rel="shortcut icon" href="{% static 'img/green-economy.png' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">

    {% block extra_styles %}
    {% endblock %}

</head>
<body class="hold-transition dark-mode sidebar-mini sidebar-collapse">
    <div class="wraper">

        {% include 'common/nav.html' %}
        {% include 'common/aside.html' %}
        <div class="content-wrapper">
            <section class="content-header">
                <div class="container-fluid">
                  <div class="row mb-2">
                    <div class="col-sm-6">
                      <h1>{{ title }}</h1>
                    </div>
                  </div>
                </div><!-- /.container-fluid -->
            </section>
            {% block content %}
            {% endblock %}
        </div>

    </div>

    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'dist/js/adminlte.min.js' %}"></script>
    {% block extra_scripts %}
    {% endblock %}
</body>
</html>

templates/common/list.html
{% extends 'common/base.html' %}
{% load static %}

{% block extra_styles %}
  <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
  {% block list_extra_styles %}
  {% endblock %}
{% endblock %}

{% block content %}
    <section class="content">
        <div class="container-fluid">
            {% block content_top %}
            {% endblock %}
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                          <h3 class="card-title">Listado {{ title }}</h3>
                          {% if new_button %}
                            <br><br>
                            <a href="{{ new_button_url }}" class="btn btn-primary"><i class="fas fa-plus-circle"></i> {{ new_button }}</a>
                          {% endif %}
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                          <table id="example1" class="table table-bordered table-striped">
                            <thead>
                              <tr>
                                {% block table_headers %}
                                {% endblock %}
                              </tr>
                            </thead>
                            <tbody>
                              {% for obj in object_list %}
                                <tr>
                                  {% block table_rows %}
                                  {% endblock %}
                                </tr>
                              {% endfor %}
                            </tbody>
                            <tfoot>
                              <tr>
                                {% block table_footer %}
                                {% endblock %}
                              </tr>
                            </tfoot>
                          </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
            {% block content_bottom %}
            {% endblock %}
        </div>
    </section>
{% endblock %}

{% block extra_scripts %}
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
    <script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
    <script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
    <script>
      $("#example1").DataTable({
        "responsive": true, "lengthChange": false, "autoWidth": false,
        "buttons": ["csv", "excel", "pdf", "colvis"]
      }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    </script>
    {% block list_extra_scripts %}
    {% endblock %}
{% endblock %}

templates/common/nav.html
{% load static %}
<nav class="main-header navbar navbar-expand navbar-dark">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'finanzas:index' %}" class="nav-link">Home</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="fas fa-user"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">Perfil de usuario</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-lock"></i> Cambiar contraseña
          </a>
          <div class="dropdown-divider"></div>
          <a href="{% url 'login:logout' %}" class="dropdown-item">
            <i class="fas fa-sign-out-alt"></i> Cerrar Sesión
          </a>
        </div>
      </li>
    </ul>
</nav>